### ISSUE TITLE
Setup for chamfer

### ISSUE THREAD

**Issue by taehyunzzz** [noahcao/Pixel2Mesh#10]
I am stuck in the code base preparation stage, specifically the line below :
`python setup.py install in directory external/chamfer and external/neural_renderer to compile the modules.
`
The error message is shown like this :
![image](https://user-images.githubusercontent.com/33646149/68663935-d1aec280-0582-11ea-9124-a5e95553be86.png)

My environment is : 
Ubuntu 16.04
Python 3.7
PyTorch 1.1
CUDA 9.0
OpenCV 3.4.0
Scipy 1.3
Scikit-Image 0.15

Could this be because of my CUDA version, that mine is not 9.2?

**Comment by ultmaster** [comment]
Did you try to Google your problem? Seems to me that it's likely due to unmatched cuda/gcc/pytorch/cudatoolkit version.

**Comment by taehyunzzz** [comment]
You are totally right. 
To my findings CUDA 9.0 seems to be incompatible with gcc-6 versions!
Should have googled more thoroughly :( Sorry for the mixup

**Comment by ultmaster** [comment]
If there are no further questions, I'm closing it. :)

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)

**Comment by YanhaoZhang** [comment]
@taehyunzzz  Hi, I got the same issue with yours. May I know how did you solve it? Thanks a lot.
