### ISSUE TITLE
How can I get the shapenet.json?

### ISSUE THREAD

**Issue by diggle1** [noahcao/Pixel2Mesh#11]
I have downloaded the part data of shapenet, but when set the tensorflow.yml, it got wrong for withouting the shapenet.json

File "/home/brl/project/Pixel2Mesh/datasets/shapenet.py", line 23, in __init__
    with open(os.path.join(self.file_root, "meta", "shapenet.json"), "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data/shapenet/meta/shapenet.json'

**Comment by ultmaster** [comment]
Hi. Thanks for raising this issue.

Seems that you somehow missed this sentence in readme: "Before that, some meta files here will help you establish the folder tree, demonstrated as follows." The link is [here](https://drive.google.com/file/d/16d9druvCpsjKWsxHmsTD5HSOWiCWtDzo/view?usp=sharing).

**Comment by diggle1** [comment]
Hi, Thanks for answering me.

Really embarrassed, it was my negligence for ignoring that sentence. Thank you for your work.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)

**Comment by diggle1** [comment]
> Hi,
> Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
> To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
> The command I use is
> 
> ```
> python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
> ```
> 
> But it seems that it only generated some meaningless meshes. And the score is really low.
> I am not sure what I did wrong.
> ![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)

Sorry, I haven't worked on this project for a long time. I've forgotten a lot of things!

**Comment by zshyang** [comment]
Hi, xiaoshudi,
Never mind. Thanks a lot for your reply. If you could recall any piece of what you did to do evaluation that would be great. If not, it is okay.
