### ISSUE TITLE
Hi, why use nn.Parameter to initialize the init_pts?

### ISSUE THREAD

**Issue by zhiwenfan** [noahcao/Pixel2Mesh#12]
thank you for your sharing. As in models/p2m.py, I donot understand why self.init_pts = nn.Parameter(ellipsoid.coord, requires_grad=False) since the init_pts do not need to train(In my understanding, init_pts just used as common input). Could you please provide some information?

**Comment by ultmaster** [comment]
Hi. Thanks for your attention. This is because we want to include the initial ellipsoid into the model such that when using this end-to-end model, we don't have to send along with the training/testing samples, an extra set of parameters, i.e., the ellipsoid, to the forward function.

**Comment by ultmaster** [comment]
Close it if it answers your question. Feel free to reopen.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
