### ISSUE TITLE
How to inference without dataset?

### ISSUE THREAD

**Issue by wanghan0501** [noahcao/Pixel2Mesh#14]
```
=> creating summary writer
Using GPUs: [0, 1, 2, 3, 4, 5, 6, 7]
Loading datasets: shapenet_demo
Running model initialization...
Traceback (most recent call last):
  File "entrypoint_predict.py", line 39, in <module>
    main()
  File "entrypoint_predict.py", line 34, in main
    predictor = Predictor(options, logger, writer)
  File "/root/workspace/DentalCastAnalysis/Pixel2Mesh/functions/predictor.py", line 20, in __init__
    super().__init__(options, logger, writer, training=False, shared_model=shared_model)
  File "/root/workspace/DentalCastAnalysis/Pixel2Mesh/functions/base.py", line 55, in __init__
    self.init_fn(shared_model=shared_model)
  File "/root/workspace/DentalCastAnalysis/Pixel2Mesh/functions/predictor.py", line 34, in init_fn
    self.ellipsoid = Ellipsoid(self.options.dataset.mesh_pos)
  File "/root/workspace/DentalCastAnalysis/Pixel2Mesh/utils/mesh.py", line 27, in __init__
    with open(file, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data/ellipsoid/info_ellipsoid.dat'
```

When I run **entrypoint_predict.py** with my own images, I get the above error messages. So my question is that how I run this code without dataset?

**Comment by ultmaster** [comment]
Hi. You have to at least put `ellipsoid` and `pretrained` in the folder. `shapenet` part can be ignored if you don't want to do training or evaluation.

**Comment by wanghan0501** [comment]
thank you.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
