### ISSUE TITLE
RuntimeError: expected scalar type Float but found Double 

### ISSUE THREAD

**Issue by hetolin** [noahcao/Pixel2Mesh#17]
Hello,Thank you for sharing your code.I follow the instruction in readme.md to train the network 
my command:
`python entrypoint_train.py --name pixel2mesh --options experiments/default/resnet.yml`
but it got errors like this:

python entrypoint_train.py --name pixel2mesh --options experiments/default/resnet.yml 
=> creating logs/pixel2mesh
=> creating checkpoints/pixel2mesh/default_resnet_0209092921
=> creating summary/pixel2mesh/default_resnet_0209092921
{'checkpoint': None,
 'checkpoint_dir': 'checkpoints/pixel2mesh/default_resnet_0209092921',
 'dataset': {'camera_c': array([111.5, 111.5]),
             'camera_f': array([248., 248.]),
             'mesh_pos': array([ 0. ,  0. , -0.8]),
             'name': 'shapenet',
             'normalization': True,
             'num_classes': 5,
             'predict': {'folder': '/tmp'},
             'shapenet': {'num_points': 9000,
                          'resize_with_constant_border': False},
             'subset_eval': 'test_tf',
             'subset_train': 'train_tf'},
 'log_dir': 'logs/pixel2mesh',
 'log_level': 'info',
 'loss': {'weights': {'chamfer': array([1., 1., 1.]),
                      'chamfer_opposite': 0.55,
                      'constant': 1.0,
                      'edge': 0.1,
                      'laplace': 0.5,
                      'move': 0.033,
                      'normal': 0.00016,
                      'reconst': 0.0}},
 'model': {'align_with_tensorflow': False,
           'backbone': 'resnet50',
           'coord_dim': 3,
           'gconv_activation': True,
           'hidden_dim': 192,
           'last_hidden_dim': 192,
           'name': 'pixel2mesh',
           'z_threshold': 0},
 'name': 'pixel2mesh',
 'num_gpus': 2,
 'num_workers': 8,
 'optim': {'adam_beta1': 0.9,
           'lr': 0.0001,
           'lr_factor': 0.3,
           'lr_step': array([30, 70, 90]),
           'name': 'adam',
           'sgd_momentum': 0.9,
           'wd': 1e-06},
 'pin_memory': True,
 'summary_dir': 'summary/pixel2mesh/default_resnet_0209092921',
 'test': {'batch_size': 8,
          'dataset': array([], dtype=float64),
          'shuffle': False,
          'summary_steps': 50,
          'weighted_mean': False},
 'train': {'batch_size': 4,
           'checkpoint_steps': 10000,
           'num_epochs': 110,
           'shuffle': True,
           'summary_steps': 50,
           'test_epochs': 1,
           'use_augmentation': True},
 'version': 'default_resnet_0209092921'}
=> creating summary writer
Using GPUs: [0, 1]
Loading datasets: shapenet
Running model initialization...
Using GPUs: [0, 1]
Loading datasets: shapenet
Running model initialization...
Checkpoint file not found, skipping...
Checkpoint not loaded
Traceback (most recent call last):
  File "entrypoint_train.py", line 39, in <module>
    main()
  File "entrypoint_train.py", line 35, in main
    trainer.train()
  File "/home/hetolin/lht/Pixel2Mesh/functions/trainer.py", line 132, in train
    out = self.train_step(batch)
  File "/home/hetolin/lht/Pixel2Mesh/functions/trainer.py", line 99, in train_step
    loss, loss_summary = self.criterion(out, input_batch)
  File "/home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hetolin/lht/Pixel2Mesh/models/losses/p2m.py", line 96, in forward
    dist1, dist2, idx1, idx2 = self.chamfer_dist(gt_coord, pred_coord[i])
  File "/home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hetolin/lht/Pixel2Mesh/models/layers/chamfer_wrapper.py", line 50, in forward
    return ChamferFunction.apply(input1, input2)
  File "/home/hetolin/lht/Pixel2Mesh/models/layers/chamfer_wrapper.py", line 26, in forward
    chamfer.forward(xyz1, xyz2, dist1, dist2, idx1, idx2)
RuntimeError: expected scalar type Float but found Double (data<float> at /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/include/ATen/core/TensorMethods.h:1386)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fe5a3a482da in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: float* at::Tensor::data<float>() const + 0xe1 (0x7fe574ab7b93 in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so)
frame #2: chamfer_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor) + 0x125 (0x7fe574ab6aa2 in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so)
frame #3: chamfer_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor) + 0xc5 (0x7fe574aaa7a5 in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0xfe96 (0x7fe574aaee96 in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0xffde (0x7fe574aaefde in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x14605 (0x7fe574ab3605 in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0x737 (0x7fe5ceca4097 in /home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #49: __libc_start_main + 0xf0 (0x7fe5dd506830 in /lib/x86_64-linux-gnu/libc.so.6)

So what is wrong with it,I did not change the code.It confused me for a long time.

**Comment by ultmaster** [comment]
Hi. Did you try to trace your error message, by printing out variable types, for example variables appeared in this line:

```
File "/home/hetolin/lht/Pixel2Mesh/models/losses/p2m.py", line 96, in forward
dist1, dist2, idx1, idx2 = self.chamfer_dist(gt_coord, pred_coord[i])
```

**Comment by hetolin** [comment]
Yes I tried to print their type, but it seem that it dose not wrong
gt_coord type:<class 'torch.Tensor'>
red_coord[i] type: <class 'torch.Tensor'>

**Comment by ultmaster** [comment]
I mean the data type. I know they are tensors...

**Comment by hetolin** [comment]
Sorry for misunderstanding, I print  the dtype of variables gt_coord and pred_coord,
gt_coord: torch.float64 
pred_coordtorch.float32

they are all float type

**Comment by ultmaster** [comment]
As you see, the chamfer loss expects float32 but instead it found float64. To find out what's wrong, you need to dig back to see where `gt_coord` comes from. A hot-fix, if you are not interested in details, is to convert `gt_coord` to float32 by `gt_coord = gt_coord.float()`.

**Comment by hetolin** [comment]
Traceback (most recent call last):
  File "entrypoint_train.py", line 39, in <module>
    main()
  File "entrypoint_train.py", line 35, in main
    trainer.train()
  File "/home/hetolin/Pixel2Mesh/functions/trainer.py", line 135, in train
    out = self.train_step(batch)
  File "/home/hetolin/Pixel2Mesh/functions/trainer.py", line 106, in train_step
    loss.backward()
  File "/home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hetolin/anaconda3/envs/pix2mesh/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function AddBackward0 returned an invalid gradient at index 0 - expected type torch.cuda.FloatTensor but got torch.cuda.DoubleTensor

I follow you instruction to convert gt_coord = gt_coord.float(), but it got errors again, I google but did not find solution.I  convert loss=loss.type(torch.FloatTensor).But it still got error above.I am really do not know what to do.

**Comment by hetolin** [comment]
Thank you for your reply.It work now! The data( I render new categories, not provided by R2N2 paper) in my .dat file is float64, but the .dat provided by R2N2 is in format float32. I fix it, and it work now, thank you for your guidance.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
