### ISSUE TITLE
 inference on your own images(real world images)

### ISSUE THREAD

**Issue by hetolin** [noahcao/Pixel2Mesh#18]
Hi，I use the network to inference on my own picture.
But I has some quetions:
1、the input image should be the same size as the image when training(224*224)?
2、the parameters `camera_c` and `camera_f` should be changed to the Len foucs of my camera?
3、the network do bad performance on real image for the difference between real image and synthetical image?
I try to modify the camera_f and camera_c, but it seems that use the default setting got the best result. 

I want to use the network to inference on real image, what can I do to narrow the gap between real and synthetical?

**Comment by ultmaster** [comment]
1. Yes. Most CV tasks require same image size for training and validation.
2. Yes. But note that since your image is rescaled to 224x224, your camera center and focus should change correspondingly.
3. You can say so. PIxel2mesh is sensitive to camera angle and position, and doesn't handle real-life images as well as images in the dataset. These are known limitations. But I highly doubt state-of-the-art methods so far are doing significantly better.

To narrow the gap, you can probably clean the background (like images in the dataset), put the object in a carefully-chosen scale, position and angle. This should prevent the model from being ridiculously wrong.

**Comment by ultmaster** [comment]
cc @noahcao cuz I'm not sure about point 3.

**Comment by hetolin** [comment]
Thank you for you reply. but I am wonder how can I determine the camera center or camera focus .It seem that I use the default camera_c and camera_f(c=111.5, f=248) in the yml file, it got the best result. so it seems that change the camera_c and camera_f don not make sense.

**Comment by ultmaster** [comment]
I think the famous picture in OpenCV might explain your question:

https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

**Comment by hetolin** [comment]
Thank you .but I am wonder that if I crop an 224x224 image from 480x640 image.should I change the camera center?

**Comment by ultmaster** [comment]
Generally speaking, if your object is in the center, and the scale is moderate, c=111.5 and f=248 is fine for you. If you are interested in details, please at least read that document.

**Comment by hetolin** [comment]
Thank you very much. I will read the document to understand the meaning of the camera parameters in detail.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
