### ISSUE TITLE
Some questions about training, hope to be answered!

### ISSUE THREAD

**Issue by TowerTowerLee** [noahcao/Pixel2Mesh#19]
**Thank you for sharing this code！**
I am a beginner of 3D reconstruction. I hope I can retrain it once, but because of the equipment problem, I can only read the code first. I have some questions that I hope to get your answers!

1.  I have noticed that `---name` in Command line for training。I wonder the `name` is the path where data is stored, or is it just a working name named by myself？

2. When evaluating use the command ` -- options path / to / YML`, should I  keep consistent with` -- options path / to / YML` selected during training? I see `self.acc_1` and `self.acc_5` in evaluator.py. I'm sorry that I can't understand the meaning of these two values very well. Can you explain?

3. If I want to train the data of single category, I only need to place the data of one category under the data-tf file, and change the `data_root = "datasets / data-tf"`?

I really admire your work and sincerely hope to get your answer！

**Comment by ultmaster** [comment]
1. Yes. You can name it anything.
2. It's for VGG16 pretraining on ImageNet, which is not very related to Pixel2Mesh.
3. Yes. And you also need to change the file list text file accordingly.

https://github.com/noahcao/Pixel2Mesh/blob/1d5011928fc209a1a67a59fbe1be62980db1884f/datasets/shapenet.py#L27

**Comment by TowerTowerLee** [comment]
https://github.com/noahcao/Pixel2Mesh/blob/1d5011928fc209a1a67a59fbe1be62980db1884f/datasets/shapenet.py#L27

Sorry, I can't understand the third point. If I need to train the "airplane" directory,should I just need to change the name of the filelist.`dataset.subset_train if training else dataset.subset_eval`？Or do I need to do with the data first? Because I see a file like JSON and TEXT opened? 
```
with open(os.path.join(self.file_root, "meta", "shapenet.json"), "r") as fp:
with open(os.path.join(self.file_root, "meta", file_list_name + ".txt"), "r") as fp:
```
I'm sorry to disturb you, but I hope to get a reply~

**Comment by TowerTowerLee** [comment]
Besides, I saw `from models.backbones import get_backbone `in the model.py  , but I can find the  `get_backbone.py`in backbones file.How can I get this file?

Hope to get your reply！

**Comment by ultmaster** [comment]
You mean you can't?

It's here:

https://github.com/noahcao/Pixel2Mesh/blob/1d5011928fc209a1a67a59fbe1be62980db1884f/models/backbones/__init__.py#L5

Maybe you should grab a Python cookbook...

**Comment by TowerTowerLee** [comment]
Thank you for your reply. It helps me a lot~

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
