### ISSUE TITLE
Some of the vertices in Face2.obj and Face3.obj do not have the correct ordering

### ISSUE THREAD

**Issue by midskavid** [noahcao/Pixel2Mesh#2]
When the generated mesh is saved, some of the normals are flipped..

**Comment by ultmaster** [comment]
According to the way that normal losses are calculated, I believe it's a flaw in Pixel2Mesh design, that it doesn't care about the positiveness/negativeness of the normal vectors. But it's worth a check.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
