### ISSUE TITLE
Training data crack.

### ISSUE THREAD

**Issue by aidendef** [noahcao/Pixel2Mesh#21]
I tried to train this project. but I occurred an error.

seline/default.yml
=> creating logs/kim
=> creating checkpoints/kim/baseline_default_0710184943
=> creating summary/kim/baseline_default_0710184943
{'checkpoint': None,
 'checkpoint_dir': 'checkpoints/kim/baseline_default_0710184943',
 'dataset': {'camera_c': [111.5, 111.5],
             'camera_f': [248.0, 248.0],
             'mesh_pos': [0.0, 0.0, -0.8],
             'name': 'shapenet',
             'normalization': True,
             'num_classes': 13,
             'predict': {'folder': '/tmp'},
             'shapenet': {'num_points': 3000,
                          'resize_with_constant_border': False},
             'subset_eval': 'test_small',
             'subset_train': 'train_small'},
 'log_dir': 'logs/kim',
 'log_level': 'info',
 'loss': {'weights': {'chamfer': [1.0, 1.0, 1.0],
                      'chamfer_opposite': 1.0,
                      'constant': 1.0,
                      'edge': 0.3,
                      'laplace': 0.5,
                      'move': 0.1,
                      'normal': 0.00016,
                      'reconst': 0.0}},
 'model': {'align_with_tensorflow': False,
           'backbone': 'vgg16',
           'coord_dim': 3,
           'gconv_activation': True,
           'hidden_dim': 192,
           'last_hidden_dim': 192,
           'name': 'pixel2mesh',
           'z_threshold': 0},
 'name': 'kim',
 'num_gpus': 2,
 'num_workers': 2,
 'optim': {'adam_beta1': 0.9,
           'lr': 5e-05,
           'lr_factor': 0.1,
           'lr_step': [30, 45],
           'name': 'adam',
           'sgd_momentum': 0.9,
           'wd': 1e-06},
 'pin_memory': True,
 'summary_dir': 'summary/kim/baseline_default_0710184943',
 'test': {'batch_size': 24,
          'dataset': [],
          'shuffle': False,
          'summary_steps': 50,
          'weighted_mean': False},
 'train': {'batch_size': 24,
           'checkpoint_steps': 10000,
           'num_epochs': 50,
           'shuffle': True,
           'summary_steps': 50,
           'test_epochs': 1,
           'use_augmentation': True},
 'version': 'baseline_default_0710184943'}
=> creating summary writer
Using GPUs: [0, 1]
Loading datasets: shapenet
Running model initialization...
Using GPUs: [0, 1]
Loading datasets: shapenet
Running model initialization...
Checkpoint file not found, skipping...
Checkpoint not loaded
Traceback (most recent call last):
  File "entrypoint_train.py", line 39, in <module>
    main()
  File "entrypoint_train.py", line 35, in main
    trainer.train()
  File "/home/ubuntu/KYG/pixel2mesh/Pixel2Mesh/functions/trainer.py", line 127, in train
    for step, batch in enumerate(train_data_loader):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/KYG/pixel2mesh/Pixel2Mesh/datasets/shapenet.py", line 53, in __getitem__
    with open(os.path.join(self.file_root, "data", label, filename), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data/shapenet/data/03001627/7eedcb6d76b8c23a9cdb421f6af95e5f_09.dat'

Could you provide your training data?
The download link seems to be wrong.
  -  https://drive.google.com/file/d/1Z8gt4HdPujBNFABYrthhau9VZW10WWYe/view
I can't download this webpage.

**Comment by noahcao** [comment]
Hi @KimYongGyu ,

We checked the googledrive link and found the files attached to it have been removed. Moreover, we haven't found a usable alternative file holder to download that full shapenet dataset because currently, we could only access the .core and .sen subsets of it on [ShapeNet](https://www.shapenet.org/about#download).

We will update the download link to the full dataset once we settle it down and confirm that it can be distributed by us. For now, I think we can't provide an alternative to it. Sorry for that.

**Comment by noahcao** [comment]
> Hi @KimYongGyu ,
> 
> We checked the googledrive link and found the files attached to it have been removed. Moreover, we haven't found a usable alternative file holder to download that full shapenet dataset because currently, we could only access the .core and .sen subsets of it on [ShapeNet](https://www.shapenet.org/about#download).
> 
> We will update the download link to the full dataset once we settle it down and confirm that it can be distributed by us. For now, I think we can't provide an alternative to it. Sorry for that.

Will keep this issue active till we find an alternative or confirm that the dataset should not be distributed by third-party like us anymore.

**Comment by noahcao** [comment]
Will keep this issue active till we find an alternative or confirm that the dataset should not be distributed by third-party like us anymore.

**Comment by noahcao** [comment]
@KimYongGyu 
We provide a temporary access to the whole dataset here: https://microsoftapc-my.sharepoint.com/:f:/g/personal/v-yugzh_microsoft_com/EucWIsg08qVKnCRxdCADzegBjU5zqjgQibgQbfeUCIbPsA?e=qskFoK

Note that this sharelink might become invalid in the short future, we will try to provide a long-term supported file host for that.

**Comment by noahcao** [comment]
As the provided link is updated in readme and @KimYongGyu hasn't followed up this issue for long, I'm closing it. Feel free to reopen it if necessary.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
