### ISSUE TITLE
Question about generating the training data

### ISSUE THREAD

**Issue by zxpzhong** [noahcao/Pixel2Mesh#23]
Hi, Thx for your reimplement. It helps me a lot.

I'm trying to run the Pixel2Mesh code. And I succeed in your provided dataset. But when I'm trying to generating the .dat file from the origin ShapeNet dataset (ShapeNetCore.v2.zip, which is downloaded from shapenet website) in the way provided by [https://github.com/nywang16/Pixel2Mesh/blob/master/GenerateData/4_make_auxiliary_dat_file.ipynb](url) , some errors occured. So could you tell me how you generated the .dat file from the origin ShapeNet dataset? 

Thx very much!

**Comment by noahcao** [comment]
Hi @zxpzhong ,

Could you provide the error information when you generated the .dat files?

Long before, I generated the .dat file following the same process. I could hardly remember if I encountered any issues.

**Comment by zxpzhong** [comment]
Hi~ Thx for your reply. I solved this already. It can be solved by just running the code in order. I didn't see previous commands in `1_sample_points.txt` so I thought that some files were missing!

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
