### ISSUE TITLE
How to generate the ellipsoid adj matrix

### ISSUE THREAD

**Issue by alexiniestags** [noahcao/Pixel2Mesh#25]
Hello, I would like to use different 3d models instead of the ellipsoid. I am trying to understand what the values of the ellipsoid mean but I am not really able to do so. I guess the .coord attribute represents the coordinates of every vertex, and in the adj_mat there are indices which I guess are the edges between vertices (?), but I do not understad what are the values part of the adj_mat.  I am not sure if I am right of my guesses. Also, the unpool_idx are the edges to apply the UnPooling operation, isn't it?
Great work and thanks in advance!

**Comment by ultmaster** [comment]
I would say your guesses are all correct. My guesses are similar.

These files are directly copied from the original Pixel2Mesh, and there is no documentation for that, as far as I know.

**Comment by noahcao** [comment]
It's a good reference for the following users. I'm closing it but please feel free to reopen it if anyone would like some follow-ups on this topic.
