### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by YDS854394028** [noahcao/Pixel2Mesh#26]
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
Does the problem mean that I should use cuda8.0 not cuda10?

**Comment by noahcao** [comment]
This is a common cuda lib linking error.

We run our codebase with CUDA9.0, but CUDA10.0 should also works (as stated in readme). So, you should check your default libcuda link's version.

**Comment by noahcao** [comment]
I'm closing this because it's not an issue in our repo. Feel free to follow-up or reopen this issue thread if you feel necessary.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
