### ISSUE TITLE
How to unzip the data folder you have provided

### ISSUE THREAD

**Issue by zshyang** [noahcao/Pixel2Mesh#27]
https://drive.google.com/drive/folders/131dH36qXCabym1JjSmEpSQZg4dmZVQid

I downloaded the data from the link above. I tried `unzip`, `7z`, and `tar`. But all of them give me an error when starting extracting.

Could you show me how to unzip the data folder?

**Comment by KhaiTTNguyen** [comment]
You have a downloading issue, try this:

Here are step-by-step instructions to download a file from Google Drive using the command line API if the file is shared privately and needs authentication.
Get the file ID:
Go to your Google Drive in your browser.
Right-click (or control-click) the file you want to download and click “Get shareable link”. The link looks like this: https://drive.google.com/open?id=XXXXX. Make note of the file ID “XXXXX”; you will be needing it below.
Get an OAuth token:
Go to OAuth 2.0 Playground
In the “Select the Scope” box, scroll down, expand “Drive API v3”, and select https://www.googleapis.com/auth/drive.readonly
Click “Authorize APIs” and then “Exchange authorization code for tokens”. Copy the “Access token”; you will be needing it below.
Download the file from the command line:
If using OS X or Linux, open the “Terminal” program and enter the following command.
curl -H "Authorization: Bearer YYYYY" https://www.googleapis.com/drive/v3/files/XXXXX?alt=media -o ZZZZZ 
If using Windows, open the “PowerShell” program and enter the following command.
Invoke-RestMethod -Uri https://www.googleapis.com/drive/v3/files/XXXXX?alt=media -Method Get -Headers @{"Authorization"="Bearer YYYYY"} -OutFile ZZZZZ 
In your command, replace “XXXXX” with the file ID from above, “YYYYY” with the access token from above, and “ZZZZZ” with the file name that will be saved (for example, “myFile.mp4” if you’re downloading an mp4 file).
Press Enter and let the download begin.
original link here: https://www.quora.com/How-do-I-download-a-very-large-file-from-Google-Drive

**Comment by noahcao** [comment]
Thanks @KhaiTTNguyen for providing the detailed solution and explanation.

@zshyang Feel free to report if you still have issues on this.

**Comment by zshyang** [comment]
@noahcao @KhaiTTNguyen ：
Thank you very much! Your reply solved my problem.
