### ISSUE TITLE
How to evaluate ShapeNet with your code and pth files.

### ISSUE THREAD

**Issue by zshyang** [noahcao/Pixel2Mesh#28]
Hi, 
Thanks for having such a great repo to hold mesh2pixel. 
Do you mind showing me what is the cmd to run the evaluation on shapenet with your YAML and pth files?
And also I have downloaded the tar pth files. but I could not unzip them. which is weird.

**Comment by ultmaster** [comment]
You can read the docs or provide more details about your problem if you intended to let us help you.

Sorry that we are not being always responsive about the issues. If it's really urgent for you, you can send email to authors and other guys in the community. I'm sure someone will be very glad to help. PLEASE DON'T REPLY TO EVERY ISSUE, as it will send tons of emails to me and blow my mailbox, which is very annoying.

Thanks for your understanding.

**Comment by zshyang** [comment]
Hi, ultmaster,

Thanks for your reply. Sorry for the inconvenience. The story is I send an issue 13 days ago as you could see. And I saw no one reply to it. And I thought this is a dead project. So to increase my chance of being replied. I ask the question under every closed issue given that it has the highest probability to get the answer. I hope you could understand. Research drives people crazy some times.

And speaking of the email, I am not sure if you provide any email address under this repo.

And speaking of other guys in the community, I am not sure is there any better way to connect to them other than asking questions under the issue they have issued.

To be more specific, my questions are:
1.
Do you know how to use their provided YAML files and pretrained weights downloaded from here `https://drive.google.com/uc?id=1pZm_IIWDUDje6gRZHW-GDhx5FCDM2Qg_&export=download` to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pre-trained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
2.
And I did not know how to unzip the pre-trained weights you have provided here `https://drive.google.com/uc?id=1pZm_IIWDUDje6gRZHW-GDhx5FCDM2Qg_&export=download`. 
The file is end with `tar`. I tried `tar -zxvf XXX.tar`. it is not working.

**Comment by ultmaster** [comment]
First of all, you might want to download checkpoints from this section: https://github.com/noahcao/Pixel2Mesh#pretrained-checkpoints

For the second question, I believe that you should ask Google for help. However, my wild guess is that, you need to remove that `z`.

**Comment by zshyang** [comment]
Hi ultmaster,
Thanks for your reply.
I did the search `https://www.google.com/search?q=how+to+untar+tar+file+in+linux&oq=how+to+untar+tar+&aqs=chrome.2.69i57j0l7.6889j0j7&sourceid=chrome&ie=UTF-8`.
And I think I am using the standard way to unzip the data **you** have provided that is the reason why I ask your help instead of google.
![Screenshot from 2020-09-22 02-44-59](https://user-images.githubusercontent.com/57812785/93867583-195fa980-fc7e-11ea-9982-66e38cf6b422.png)
![Screenshot from 2020-09-22 02-45-26](https://user-images.githubusercontent.com/57812785/93867591-1bc20380-fc7e-11ea-9289-6883be9514d8.png)
![Screenshot from 2020-09-22 02-46-02](https://user-images.githubusercontent.com/57812785/93867595-1d8bc700-fc7e-11ea-9945-c372fe8b3051.png)
![Screenshot from 2020-09-22 02-50-19](https://user-images.githubusercontent.com/57812785/93867794-6774ad00-fc7e-11ea-9693-d248bf182def.png)

**Comment by ultmaster** [comment]
You should not extract resnet.pth.tar. It's a PyTorch checkpoint. Please load it directly.

**Comment by zshyang** [comment]
That makes sense. Thank you so much!

**Comment by zshyang** [comment]
One more question,
I run the following command:
```
python entrypoint_eval.py --name xxx --options experiments/default/resnet.yml --checkpoint datasets/data/pretrained/resnet.pth.tar 
```
And the evaluation results are:
![Screenshot from 2020-09-22 13-15-22](https://user-images.githubusercontent.com/57812785/93932969-cdd8ea00-fcd5-11ea-9c08-8f45a2c9e96d.png)
which is quite a way from the reported number. Did I do something wrong with the input of the evaluation code?

**Comment by noahcao** [comment]
I'm closing this issue as the it has been resolved. For the issue of evaluation performance please raise that for discussion in a new issue thread.
