### ISSUE TITLE
The evaluation result does not match with reported results

### ISSUE THREAD

**Issue by zshyang** [noahcao/Pixel2Mesh#29]
Hi,
I am trying to reproduce your numbers.
I run the following command:
```
python entrypoint_eval.py --name xxx --options experiments/default/resnet.yml --checkpoint datasets/data/pretrained/resnet.pth.tar 
```
And the evaluation results are:
![Screenshot from 2020-09-22 13-15-22](https://user-images.githubusercontent.com/57812785/93932969-cdd8ea00-fcd5-11ea-9c08-8f45a2c9e96d.png)
which is quite a way from the reported number. Did I do something wrong with the input of the evaluation code?

**Comment by noahcao** [comment]
Where did you get the checkpoint model: datasets/data/pretrained/resnet.pth.tar ?

**Comment by zshyang** [comment]
Yes.

**Comment by noahcao** [comment]
Sorry, I asked... where did you get the checkpoint.... downloaded it through the link we provided?

**Comment by noahcao** [comment]
I tested the checkpoint we provided, it looks fine. I'm closing this issue. Feel free to followup if you still have problem for that.

**Comment by fighting-Zhang** [comment]
I got the same problem. I downloaded checkpoints through the link you provided, and used experiments/default/resnet.yml as options. The result is the same as @zshyang .

**Comment by sksnb** [comment]
Hello I also had the same issue, did you fix this issue
