### ISSUE TITLE
I have a problem, could you please help me? Thanks

### ISSUE THREAD

**Issue by A-Little-Nut** [noahcao/Pixel2Mesh#30]
Thanks for sharing your code with us!
I have a problem during runing your codes.
`No module name chamfer`
I have run your scripts, but why?
What should I do?
Thanks

**Comment by noahcao** [comment]
please compile the modules in external/chamfer.

**Comment by noahcao** [comment]
Because this is a problem that could be fixed by following the guidelines in the readme, I'm closing it. Please feel free to follow-up or reopen it if necessary.
