### ISSUE TITLE
Import error of Chamfer loss

### ISSUE THREAD

**Issue by SnehithR** [noahcao/Pixel2Mesh#31]
when I run python setupy.py install there were no errors, But when i tried to import chamfer module the following error occurs.

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import chamfer
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

TIA

**Comment by noahcao** [comment]
It's an error related to your pytorch lib install. Please refer to the installation guidelines of pytorch to fix it.
