### ISSUE TITLE
edge loss is not correct

### ISSUE THREAD

**Issue by YanhaoZhang** [noahcao/Pixel2Mesh#35]
Hi, it seems that the edge loss is not correct. It should penalize the change of edge length, not just the distance of edges from the predicted edge. https://github.com/noahcao/Pixel2Mesh/blob/92a6f7bdbee56e26c4a3e33c5974e6571d12676f/models/losses/p2m.py#L20-L26

**Comment by noahcao** [comment]
I think our implementation follows the paper design. Also, we double checked the official tensorflow implementation, the corresponding loss is [here](https://github.com/nywang16/Pixel2Mesh/blob/7c5a7a142d5f64f15250f9e98ee496980f69e005/p2m/losses.py#L53) for your reference.
