### ISSUE TITLE
undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv

### ISSUE THREAD

**Issue by hugo-xie** [noahcao/Pixel2Mesh#5]
hello， I got a problem when I training the model.Traceback (most recent call last):
`File "entrypoint_train.py", line 4, in <module>
    from functions.trainer import Trainer
  File "/home/xy/project/Pixel2Mesh/functions/trainer.py", line 9, in <module>
    from functions.evaluator import Evaluator
  File "/home/xy/project/Pixel2Mesh/functions/evaluator.py", line 10, in <module>
    from models.layers.chamfer_wrapper import ChamferDist
  File "/home/xy/project/Pixel2Mesh/models/layers/chamfer_wrapper.py", line 1, in <module>
    import chamfer
ImportError: /home/xy/anaconda3/lib/python3.6/site-packages/chamfer-0.0.0-py3.6-linux-x86_64.egg/chamfer.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv`

Am I doing something wrong?
Thanks

**Comment by ultmaster** [comment]
What's your PyTorch version? CUDA version?

Generally speaking, you should Google it first before raising an issue. For example, I found this for you: facebookresearch/maskrcnn-benchmark#813

**Comment by hugo-xie** [comment]
@ultmaster Thank you for your reply，yes, I google it before，But it has not been solved，My pytorch version: 1.1 and cuda version:9 ,  torchvision version: 0.4.0, what's your torchvision version?
Thanks

**Comment by ultmaster** [comment]
@hugo-xie From my experience, this kind of problem is usually caused by conflicting/multiple PyTorch/torchvision/CUDA/numpy versions. Try to create a clean environment, do the cleanup and try it again.

My torchvision is 0.4.0. Your package versions seem fine to me.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
