### ISSUE TITLE
Chamfer doesn't work with CUDA 10.1 and PyTorch 1.3

### ISSUE THREAD

**Issue by Pyten** [noahcao/Pixel2Mesh#6]
Thank you for the excellent repo. According to your instructions, I clone your repo and install 2 external modules. But when running the entrypoin_train.py, I met the following problem.
![image](https://user-images.githubusercontent.com/38207414/67663664-fe6ab380-f9a0-11e9-991d-32d350034ebd.png)
I tried to locate the problem, only to find that the problem was happening in the chamfer module. So I am wondering could you please share your compiling environments such as your system version and gcc version? Or if you have some clues, please let me know. Thank you!

**Comment by ultmaster** [comment]
@PTL2011 Thanks for reporting this issue. Our chamfer is tested on both ubuntu 16.04 and 18.04, with default gcc, which I believe was something between 4.9 and 5.4.

Also try to downgrade to PyTorch 1.1 to see if that works.

**Comment by Pyten** [comment]
@ultmaster Thank you! Your information indeed is of help. I try to duplicate your environment, but something was wrong. Maybe it was due to my Cuda version, which is 10.1. Then I degrade my PyTorch to 1.2, torchvision to 0.4.0 and cudatoolkit to 10.0, which really works fine until now. 
Btw, since this is my 1st project in 3D-field, I am very confused with tuning the parameters to converge faster and to get ideal results. So, could you please share your training parameters in your experiment, or could you give me some advice?

**Comment by ultmaster** [comment]
I believe all the parameters have been listed in the yml file. The results should be reproducible with those settings.

**Comment by Pyten** [comment]
@ultmaster Thanks a lot! The resnet.yml works well. I checked the internet and found that the shapenet should be OBJ format. Would you mind tell me what kind of information is included in the .dat file, or what's the relation with the original OBJ file?

**Comment by ultmaster** [comment]
Yes. The .dat file is a rendered shapenet object (image) with a specific angle and lighting, along with the ground truth pointcloud. You can find how to read these files [here](https://github.com/noahcao/Pixel2Mesh/blob/master/datasets/shapenet.py). I believe the rendering was done by the guys who published 3D-R2N2, but I'm not sure.

**Comment by ultmaster** [comment]
If there are no updates, I'm closing this issue.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
