### ISSUE TITLE
When I was running the usage, it said the optimizers not found in the runner, skipping...

### ISSUE THREAD

**Issue by darkzyf** [noahcao/Pixel2Mesh#7]
When I was running the usage, it said the optimizers not found in the runner, skipping...
Could you please tell me where is the wrong?

**Comment by ultmaster** [comment]
It's just a logging message. You can ignore that.

**Comment by darkzyf** [comment]
I see , Thank you very mcuh.

**Comment by noahcao** [comment]
If there no issue already, I will close this thread.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)

**Comment by santosh-shriyan** [comment]
I think that it is not able to use the gpu for inference and shifts to cpu usage as I observed the same.
Using a single cpu thread and no gpu usage and so takes a very long time.

Can anyone tell me how I can fix it.

![Screenshot from 2022-02-04 16-17-41](https://user-images.githubusercontent.com/63632331/152516228-9fcfcf45-95c8-4eef-adb3-d8d310dfc2fa.png)
