### ISSUE TITLE
The meta files

### ISSUE THREAD

**Issue by darkzyf** [noahcao/Pixel2Mesh#8]
Hello, I download the meta files, I have a question about the pretrained model. Is this three models  be trained on the shapenet dataset?

**Comment by ultmaster** [comment]
Hi, the pretrained checkpoints here are exactly the ones provided in torchvision, except for `vgg16-p2m`, which is a vgg16 modified by Pixel2Mesh (less layers, fewer BNs), pretrained on ImageNet.

We tried using `vgg16-p2m` for training, but as it didn't workout as expected, we didn't release our final training model.

**Comment by darkzyf** [comment]
Thank you very much~

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
